"""Processor for Parler-TTS."""

from typing import Any

import numpy as np

from transformers.processing_utils import ProcessorMixin
from transformers.utils import to_numpy


class ParlerTTSProcessor(ProcessorMixin):
    r"""
    Constructs a Parler-TTS processor which combines a text tokenizer and the `DacModel` audio tokenizer used to
    decode generated audio codes back into a waveform.

    [`ParlerTTSProcessor`] offers all the functionalities of the text tokenizer and, once given an
    [`~ParlerTTSProcessor.decode`] call, of [`DacModel`]. See [`~ParlerTTSProcessor.__call__`] and
    [`~ParlerTTSProcessor.decode`] for more information.

    Args:
        tokenizer (`PreTrainedTokenizerBase`, *optional*):
            The text tokenizer used to encode both the voice description and the text prompt.
        audio_tokenizer ([`DacModel`], *optional*):
            The audio codec that decodes generated audio codes into waveforms.
    """

    attributes = ["tokenizer"]
    tokenizer_class = "AutoTokenizer"
    audio_tokenizer_class = "DacModel"

    def __init__(self, tokenizer=None, audio_tokenizer=None):
        super().__init__(tokenizer, audio_tokenizer=audio_tokenizer)

    def __call__(self, text: str | list[str], description: str | list[str], **kwargs) -> Any:
        """
        Prepares text and voice-description inputs for [`ParlerTTSForConditionalGeneration.generate`].

        Args:
            text (`str` or `List[str]`):
                The text prompt(s) to synthesize into speech.
            description (`str` or `List[str]`):
                Natural-language description(s) of the desired voice and delivery style.
            **kwargs:
                Additional keyword arguments forwarded to the tokenizer.

        Returns:
            [`BatchFeature`]: Contains `input_ids`/`attention_mask` for `description` and
            `prompt_input_ids`/`prompt_attention_mask` for `text`, ready to be passed to
            [`ParlerTTSForConditionalGeneration.generate`].
        """
        kwargs.setdefault("return_tensors", "pt")
        kwargs.setdefault("padding", True)

        encoded_description = self.tokenizer(description, **kwargs)
        encoded_prompt = self.tokenizer(text, **kwargs)

        return {
            "input_ids": encoded_description["input_ids"],
            "attention_mask": encoded_description["attention_mask"],
            "prompt_input_ids": encoded_prompt["input_ids"],
            "prompt_attention_mask": encoded_prompt["attention_mask"],
        }

    def decode(self, audio_codes, padding_mask: Any = None) -> tuple[list[np.ndarray], int]:
        """
        Decodes audio codes generated by [`ParlerTTSForConditionalGeneration.generate`] into waveforms using the
        `audio_tokenizer`.

        Args:
            audio_codes (`torch.LongTensor` of shape `(batch_size, num_codebooks, sequence_length)`):
                Audio codes generated by the model.
            padding_mask (`torch.Tensor`, *optional*):
                Mask used to strip padding from the decoded waveforms.

        Returns:
            `tuple(list[np.ndarray], int)`: The decoded waveforms and the audio tokenizer's sampling rate.
        """
        if self.audio_tokenizer is None:
            raise ValueError(
                "This processor was not instantiated with an `audio_tokenizer`. Load it with "
                "`ParlerTTSProcessor.from_pretrained(...)` from a Parler-TTS checkpoint."
            )
        audio_codes = audio_codes.to(self.audio_tokenizer.device)
        audio_values = self.audio_tokenizer.decode(audio_codes=audio_codes[None, ...]).audio_values

        return self._strip_padding(audio_values, padding_mask), self.audio_tokenizer.config.sampling_rate

    @staticmethod
    def _strip_padding(audio_values, padding_mask: Any = None) -> list[np.ndarray]:
        audio_values = to_numpy(audio_values)
        bsz, channels, seq_len = audio_values.shape

        if padding_mask is None:
            return list(audio_values)

        padding_mask = to_numpy(padding_mask)
        difference = seq_len - padding_mask.shape[-1]
        padding_mask = np.pad(padding_mask, ((0, 0), (0, max(difference, 0))), "constant", constant_values=1)

        stripped = []
        for i in range(bsz):
            sliced_audio = np.asarray(audio_values[i])[padding_mask[i][None, :] != 0]
            stripped.append(sliced_audio.reshape(channels, -1))

        return stripped


__all__ = ["ParlerTTSProcessor"]
